# .zshrc

# basic PATH
export PATH="$HOME/bin:/usr/local/bin:$PATH"
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

# custom PATH
# export PATH = 

# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/custom/themes/powerlevel10k/powerlevel10k.zsh-theme

autoload -U compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

setopt print_eight_bit
setopt no_beep
setopt hist_ignore_dups
setopt extended_glob
setopt share_history
setopt hist_reduce_blanks

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# aliases
if [ -f $HOME/.aliases ]; then
  source $HOME/.aliases
fi

