require("base") 
require("plugins")

--require("plugins/coc")
require("plugins/lspconfig")
--require("plugins/copilot")
require("plugins/nvim-tree")
require("plugins/harpoon")
require("plugins/lualine")
require("plugins/telescope")
require("plugins/treesitter")
require("plugins/undotree")
require("plugins/nightfox")
