require("base")
require("plugins")

require("plugins/lspconfig")
require("plugins/none-ls")
require("plugins/noice")
require("plugins/indent-blackline")
require("plugins/lualine")
require("plugins/fidget")
require("plugins/undotree")
require("plugins/nvim-tree")
require("plugins/telescope")
require("plugins/harpoon")
require("plugins/nightfox")
require("plugins/gitsigns")
